name: Continuous Integration

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
      packageVersionSuffix: ${{ github.ref == 'refs/heads/develop' && 'pre-' ||  'ci-' }}${{github.RUN_NUMBER }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      if:  ${{ github.ref == 'refs/heads/main' }}
      run: dotnet build --no-restore --configuration ${{ env.buildConfiguration }}
    - name: Build (Prerelease version)
      if:  ${{ github.ref != 'refs/heads/main' }}
      run: dotnet build --no-restore --configuration ${{ env.buildConfiguration }} --version-suffix ${{ env.packageVersionSuffix }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ env.buildConfiguration }}
    - name: Pack
      if:  ${{ github.ref == 'refs/heads/main' }}
      run: dotnet pack --no-build --no-restore --configuration ${{ env.buildConfiguration }} -o out
    - name: Pack (Prerelease version)
      if:  ${{ github.ref != 'refs/heads/main' }}
      run: dotnet pack --no-build --no-restore --configuration ${{ env.buildConfiguration }} --version-suffix ${{ env.packageVersionSuffix }}
    - name: Publish packages
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/stefanolsen/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
